spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sprinkle
    username: sprinkle
    password: 1234
    hikari:
      maximum-pool-size: 50
      connection-timeout: 5000
      validation-timeout: 1000


  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: false
    hibernate:
      format_sql: true
      ddl-auto: create-drop

logging:

  level:
    root: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: DEBUG